


paths: 
  root_dir_win: T:\\\\
  root_dir_posix: /Volumes/Quantum2/


endpoint_list: 
    - LIGHTSPEED1
    - LIGHTSPEED2
    - LIGHTSPEED3
    - LIGHTSPEED4
    - LIGHTSPEED5
    - LIGHTSPEED6
    - LIGHTSPEED7
    - FNDC-VANLSG6-08
    - FNDC-VANLSG6-09
    - FNDC-VANLSG6-10
    - FNDC-VANLSG6-11
    - FNDC-VANLSG6-12

