---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s | %(levelname)s | Function: %(funcName)s() | Line %(lineno)s | %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ./_logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: ./_logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    main:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

root:
    level: NOTSET
    handlers: [console, info_file_handler, error_file_handler]
    propogate: yes
...